from figspec.document import DesignerDocument
from figspec.snippet import generate_snippet


def test_snippet_content():
    doc = DesignerDocument.default()
    spec = doc.to_spec_dict()
    text = generate_snippet(spec, name="fig1.json")
    assert text.startswith("# Generated by FigSpec Designer from fig1.json")
    assert "regenerate after layout changes" in text
    assert "import matplotlib.pyplot as plt" in text
    assert '"font.size": 5.0' in text
    assert f'"axes.linewidth": {spec["constraints"]["min_linewidth_pt"]}' in text
    assert '"pdf.fonttype": 42' in text
    assert '"svg.fonttype": "none"' in text
    # per-panel block for panel a (default doc = single full-page panel)
    p = spec["panels"][0]
    assert f"figsize=({p['figsize_in'][0]}, {p['figsize_in'][1]})" in text
    assert f"dpi={spec['target']['dpi']}" in text
    assert 'fig_a.savefig("panel_a.pdf")' in text
    assert f"# panel a: {p['w_mm']} × {p['h_mm']} mm" in text


def test_snippet_includes_content_hint():
    doc = DesignerDocument.default()
    spec = doc.to_spec_dict()
    spec["panels"][0]["content_hint"] = "STEM image"
    text = generate_snippet(spec)
    assert "STEM image" in text
    assert "from Untitled" in text
