"""Batch C UI tests: snippet, assets, DPI light, preview export, templates."""
from PySide6.QtWidgets import QApplication

from figspec.layout.tree import iter_panels
from figspec_designer.ui.main_window import MainWindow


def test_copy_snippet_button(qtbot):
    win = MainWindow()
    qtbot.addWidget(win)
    win.sidebar.btn_copy_snippet.click()
    text = QApplication.clipboard().text()
    assert text.startswith("# Generated by FigSpec Designer from Untitled")
    assert "plt.rcParams.update" in text
