"""Batch C UI tests: snippet, assets, DPI light, preview export, templates."""
from PySide6.QtWidgets import QApplication

from figspec.layout.tree import iter_panels
from figspec_designer.ui.main_window import MainWindow


def test_copy_snippet_button(qtbot):
    win = MainWindow()
    qtbot.addWidget(win)
    win.sidebar.btn_copy_snippet.click()
    text = QApplication.clipboard().text()
    assert text.startswith("# Generated by FigSpec Designer from Untitled")
    assert "plt.rcParams.update" in text


def _make_png(tmp_path, w=400, h=300, name="asset.png"):
    from PySide6.QtGui import QImage
    img = QImage(w, h, QImage.Format_RGB32)
    img.fill(0xFFFFFFFF)
    path = tmp_path / name
    img.save(str(path))
    return path


def test_asset_drop_sets_external_state(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    panel = next(iter_panels(win.doc.tree))
    assert panel.asset == str(png)
    assert panel.asset_px == (400, 300)
    assert win.dirty
    # canvas widget shows a thumbnail
    widget = win.canvas.panel_widgets()[pid]
    assert widget._thumb is not None


def test_asset_drop_unreadable_file(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    bad = tmp_path / "not_an_image.png"
    bad.write_bytes(b"garbage")
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(bad))
    assert next(iter_panels(win.doc.tree)).asset is None  # rejected, no crash


def test_missing_asset_flagged(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    png.unlink()  # asset vanishes from disk
    win.refresh()
    widget = win.canvas.panel_widgets()[pid]
    assert widget.property("assetMissing") is True
    assert widget._thumb is None


def test_drag_enter_accepts_image_urls(qtbot, tmp_path):
    from PySide6.QtCore import QMimeData, QUrl
    win = MainWindow()
    qtbot.addWidget(win)
    pid = next(iter_panels(win.doc.tree)).id
    widget = win.canvas.panel_widgets()[pid]
    mime = QMimeData()
    mime.setUrls([QUrl.fromLocalFile(str(tmp_path / "x.TIF"))])
    assert widget._accepts_mime(mime)  # case-insensitive ext
    mime2 = QMimeData()
    mime2.setUrls([QUrl.fromLocalFile(str(tmp_path / "x.pdf"))])
    assert not widget._accepts_mime(mime2)


def test_open_json_resolves_relative_assets_before_render(qtbot, tmp_path):
    # Regression: open_json() used to call refresh() before setting
    # current_path, so the first render after File > Open resolved
    # relative asset paths against a stale/None base dir and falsely
    # flagged every present asset as missing.
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    json_path = tmp_path / "figspec.json"
    win.save_json(json_path)  # relativizes the asset path in the saved JSON

    win2 = MainWindow()
    qtbot.addWidget(win2)
    err = win2.open_json(str(json_path))
    assert err is None
    pid2 = next(iter_panels(win2.doc.tree)).id
    widget = win2.canvas.panel_widgets()[pid2]
    assert widget.property("assetMissing") is False
    assert widget._thumb is not None


def test_sidebar_asset_block_and_dpi_light(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path, 400, 300)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    win.do_action("select", pid)
    sb = win.sidebar
    assert sb.asset_box.isVisibleTo(sb)  # offscreen-safe visibility check
    assert sb.lbl_asset_name.text() == "asset.png"
    assert sb.lbl_asset_px.text() == "400 × 300 px"
    # default panel 183x100mm: eff dpi = min(400/7.2in, 300/3.94in) ~ 55 -> red
    assert sb.lbl_asset_dpi.property("level") == "bad"
    assert "dpi" in sb.lbl_asset_dpi.text()


def test_sidebar_remove_asset(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    win.do_action("select", pid)
    win.sidebar.btn_remove_asset.click()
    assert next(iter_panels(win.doc.tree)).asset is None
    win.do_action("select", pid)
    assert not win.sidebar.asset_box.isVisibleTo(win.sidebar)


def test_dpi_levels(qtbot, tmp_path):
    # a big asset on the default 183x100 panel: 8000x5000 -> ~1270 dpi -> ok
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path, 80, 50, "big.png")  # tiny file, fake px via ops
    pid = next(iter_panels(win.doc.tree)).id
    from figspec.layout import ops
    win._push_tree(ops.set_asset(win.doc.tree, pid, str(png), (8000, 5000)))
    win.do_action("select", pid)
    assert win.sidebar.lbl_asset_dpi.property("level") == "ok"
