"""Batch C UI tests: snippet, assets, DPI light, preview export, templates."""
from PySide6.QtWidgets import QApplication

from figspec.layout.tree import iter_panels
from figspec_designer.ui.main_window import MainWindow


def test_copy_snippet_button(qtbot):
    win = MainWindow()
    qtbot.addWidget(win)
    win.sidebar.btn_copy_snippet.click()
    text = QApplication.clipboard().text()
    assert text.startswith("# Generated by FigSpec Designer from Untitled")
    assert "plt.rcParams.update" in text


def _make_png(tmp_path, w=400, h=300, name="asset.png"):
    from PySide6.QtGui import QImage
    img = QImage(w, h, QImage.Format_RGB32)
    img.fill(0xFFFFFFFF)
    path = tmp_path / name
    img.save(str(path))
    return path


def test_asset_drop_sets_external_state(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    panel = next(iter_panels(win.doc.tree))
    assert panel.asset == str(png)
    assert panel.asset_px == (400, 300)
    assert win.dirty
    # canvas widget shows a thumbnail
    widget = win.canvas.panel_widgets()[pid]
    assert widget._thumb is not None


def test_asset_drop_unreadable_file(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    bad = tmp_path / "not_an_image.png"
    bad.write_bytes(b"garbage")
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(bad))
    assert next(iter_panels(win.doc.tree)).asset is None  # rejected, no crash


def test_missing_asset_flagged(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    png.unlink()  # asset vanishes from disk
    win.refresh()
    widget = win.canvas.panel_widgets()[pid]
    assert widget.property("assetMissing") is True
    assert widget._thumb is None


def test_drag_enter_accepts_image_urls(qtbot, tmp_path):
    from PySide6.QtCore import QMimeData, QUrl
    win = MainWindow()
    qtbot.addWidget(win)
    pid = next(iter_panels(win.doc.tree)).id
    widget = win.canvas.panel_widgets()[pid]
    mime = QMimeData()
    mime.setUrls([QUrl.fromLocalFile(str(tmp_path / "x.TIF"))])
    assert widget._accepts_mime(mime)  # case-insensitive ext
    mime2 = QMimeData()
    mime2.setUrls([QUrl.fromLocalFile(str(tmp_path / "x.pdf"))])
    assert not widget._accepts_mime(mime2)


def test_open_json_resolves_relative_assets_before_render(qtbot, tmp_path):
    # Regression: open_json() used to call refresh() before setting
    # current_path, so the first render after File > Open resolved
    # relative asset paths against a stale/None base dir and falsely
    # flagged every present asset as missing.
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    json_path = tmp_path / "figspec.json"
    win.save_json(json_path)  # relativizes the asset path in the saved JSON

    win2 = MainWindow()
    qtbot.addWidget(win2)
    err = win2.open_json(str(json_path))
    assert err is None
    pid2 = next(iter_panels(win2.doc.tree)).id
    widget = win2.canvas.panel_widgets()[pid2]
    assert widget.property("assetMissing") is False
    assert widget._thumb is not None


def test_sidebar_asset_block_and_dpi_light(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path, 400, 300)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    win.do_action("select", pid)
    sb = win.sidebar
    assert sb.asset_box.isVisibleTo(sb)  # offscreen-safe visibility check
    assert sb.lbl_asset_name.text() == "asset.png"
    assert sb.lbl_asset_px.text() == "400 × 300 px"
    # default panel 183x100mm: eff dpi = min(400/7.2in, 300/3.94in) ~ 55 -> red
    assert sb.lbl_asset_dpi.property("level") == "bad"
    assert "dpi" in sb.lbl_asset_dpi.text()
    # File/Pixels rows must share the same styled-value objectName as the
    # rest of the sidebar's value labels; the DPI label keeps its own
    # level-colored name instead.
    assert sb.lbl_asset_name.objectName() == "fieldValue"
    assert sb.lbl_asset_px.objectName() == "fieldValue"
    assert sb.lbl_asset_dpi.objectName() == "dpiValue"


def test_sidebar_remove_asset(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path)
    pid = next(iter_panels(win.doc.tree)).id
    win._on_asset_dropped(pid, str(png))
    win.do_action("select", pid)
    win.sidebar.btn_remove_asset.click()
    assert next(iter_panels(win.doc.tree)).asset is None
    win.do_action("select", pid)
    assert not win.sidebar.asset_box.isVisibleTo(win.sidebar)


def test_dpi_levels(qtbot, tmp_path):
    # a big asset on the default 183x100 panel: 8000x5000 -> ~1270 dpi -> ok
    win = MainWindow()
    qtbot.addWidget(win)
    png = _make_png(tmp_path, 80, 50, "big.png")  # tiny file, fake px via ops
    pid = next(iter_panels(win.doc.tree)).id
    from figspec.layout import ops
    win._push_tree(ops.set_asset(win.doc.tree, pid, str(png), (8000, 5000)))
    win.do_action("select", pid)
    assert win.sidebar.lbl_asset_dpi.property("level") == "ok"


def test_render_layout_png(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    pid = next(iter_panels(win.doc.tree)).id
    win.do_action("split_right", pid)
    out = tmp_path / "layout.png"
    from figspec_designer.ui.preview_export import render_layout_png
    render_layout_png(win.doc, out)
    assert out.exists() and out.stat().st_size > 0
    from PySide6.QtGui import QImage
    img = QImage(str(out))
    # 183mm page at 4 px/mm * scale 2 = 1464 px wide, page + footer tall
    assert img.width() == round(183.0 * 8)
    assert img.height() > round(100.0 * 8)


def test_render_layout_image_standalone_tree(qtbot):
    from figspec.templates import TEMPLATES
    from figspec.spec import Target
    from figspec_designer.ui.preview_export import render_layout_image
    img = render_layout_image(TEMPLATES["hero_left"].build(),
                              Target("nature_double", 183.0, 100.0),
                              scale=1)
    assert not img.isNull()
    assert img.width() == round(183.0 * 4)


def test_fits_predicate_narrow_vs_wide(qtbot):
    # Unit check of the width/height predicate used to decide whether an
    # annotation is drawn at all — a narrow rect should reject a normal
    # label, a generously sized one should accept it.
    from PySide6.QtCore import QRectF
    from PySide6.QtGui import QFont, QFontMetrics
    from figspec_designer.ui.preview_export import _fits
    fm = QFontMetrics(QFont())
    text = "0.5 × 100.0 mm"
    tiny_rect = QRectF(0, 0, 5, 20)
    big_rect = QRectF(0, 0, 400, 40)
    assert not _fits(fm, text, tiny_rect, margin_px=4)
    assert _fits(fm, text, big_rect, margin_px=4)


def test_narrow_panel_renders_without_text_bleed(qtbot):
    # Regression: a sub-3mm-wide panel used to have its letter/mm-size
    # annotation drawn unclipped, bleeding ink past its own frame line.
    # With the fits() skip-logic, no dark (letter-colored) ink should
    # appear anywhere within — or just past — such a narrow panel's column.
    from figspec.layout.tree import PanelNode, SplitNode
    from figspec.layout.flatten import flatten
    from figspec.spec import Target
    from figspec_designer.ui.preview_export import render_layout_image, PX_PER_MM

    tree = SplitNode("row", (0.01, 0.99),
                     (PanelNode(id="narrow"), PanelNode(id="wide")))
    target = Target("nature_double", 183.0, 100.0)
    scale = 2
    img = render_layout_image(tree, target, scale=scale)
    assert not img.isNull()
    # smoke: page stays within the expected pixel bounds
    assert img.width() == round(target.figure_width_mm * PX_PER_MM * scale)
    assert img.height() >= round(target.figure_height_mm * PX_PER_MM * scale)

    ppm = PX_PER_MM * scale
    rects = {r.panel_id: r for r in flatten(
        tree, target.figure_width_mm, target.figure_height_mm, target.gutter_mm)}
    narrow = rects["narrow"]
    x0 = round(narrow.x_mm * ppm)
    x1 = max(x0 + 1, round((narrow.x_mm + narrow.w_mm) * ppm))
    y0 = round(narrow.y_mm * ppm)
    y1 = min(round((narrow.y_mm + narrow.h_mm) * ppm), y0 + 60)  # top strip only

    # Letter ink is near-black; frame strokes and page background are much
    # lighter. If the skip-logic failed, the letter/mm text would paint
    # dark pixels across this narrow panel's column.
    for x in range(x0, x1):
        for y in range(y0, y1):
            assert img.pixelColor(x, y).lightness() >= 100


def test_render_layout_png_returns_bool(qtbot, tmp_path):
    win = MainWindow()
    qtbot.addWidget(win)
    from figspec_designer.ui.preview_export import render_layout_png
    ok_path = tmp_path / "layout.png"
    assert render_layout_png(win.doc, ok_path) is True
    assert ok_path.exists()

    bad_path = tmp_path / "missing_dir" / "layout.png"
    assert render_layout_png(win.doc, bad_path) is False
    assert not bad_path.exists()


def test_export_layout_preview_appends_png_suffix_and_reports_success(
        qtbot, tmp_path, monkeypatch):
    from PySide6.QtWidgets import QFileDialog
    win = MainWindow()
    qtbot.addWidget(win)
    chosen = str(tmp_path / "layout")  # no suffix typed by the user
    monkeypatch.setattr(QFileDialog, "getSaveFileName",
                        staticmethod(lambda *a, **k: (chosen, "")))
    win.export_layout_preview()
    out = tmp_path / "layout.png"
    assert out.exists() and out.stat().st_size > 0
    assert win.statusBar().currentMessage() == f"Layout preview exported to {out}"


def test_export_layout_preview_write_failure_reports_status_no_crash(
        qtbot, tmp_path, monkeypatch):
    from PySide6.QtWidgets import QFileDialog
    win = MainWindow()
    qtbot.addWidget(win)
    bad = tmp_path / "does_not_exist" / "layout.png"
    monkeypatch.setattr(QFileDialog, "getSaveFileName",
                        staticmethod(lambda *a, **k: (str(bad), "")))
    win.export_layout_preview()  # must not raise
    assert win.statusBar().currentMessage() == f"Could not write {bad}"
    assert not bad.exists()
