"""figspec.json -> matplotlib starter code. Pure string generation, shared
by the Designer and (later) the MCP server. Interim tool: retires once M1
server-side rendering lands."""
from __future__ import annotations


def generate_snippet(spec: dict, name: str = "Untitled") -> str:
    c = spec["constraints"]
    dpi = spec["target"]["dpi"]
    font = c["min_font_pt"]
    lines = [
        f"# Generated by FigSpec Designer from {name} — "
        "regenerate after layout changes",
        "import matplotlib.pyplot as plt",
        "",
        "plt.rcParams.update({",
        f'    "font.size": {font},',
        f'    "axes.labelsize": {font},',
        f'    "xtick.labelsize": {font},',
        f'    "ytick.labelsize": {font},',
        f'    "legend.fontsize": {font},',
        f'    "axes.linewidth": {c["min_linewidth_pt"]},',
        '    "pdf.fonttype": 42,',
        '    "svg.fonttype": "none",',
        "})",
        "",
    ]
    for p in spec["panels"]:
        var = p["label"]
        hint = f" — {p['content_hint']}" if p.get("content_hint") else ""
        fw, fh = p["figsize_in"]
        lines += [
            f"# panel {var}: {p['w_mm']} × {p['h_mm']} mm{hint}",
            f"fig_{var}, ax_{var} = plt.subplots(figsize=({fw}, {fh}), dpi={dpi})",
            f'fig_{var}.savefig("panel_{var}.pdf")',
            "",
        ]
    return "\n".join(lines)
